export const SNOWY_WINDOW_CONFIG = {
  canvas: { width: 720, height: 1280 },
  condensation: {
    initialDensity: 0.78,
    growthSpeed: 0.035,
    noiseScale: 3.2,
    driftSpeed: 0.018,
    wipeStrength: 1.15,
    mouthRefillStrength: 12,
    wipeDisplacement: 0.18,
    wipeResidue: 0.22,
    wipeResidueDrySpeed: 0.45,
    wipeClearThreshold: 0.015,
    wipeGrowthDelay: 0.8,
    filmOpacity: 0.28,
    dropletOpacity: 0.48,
    dropletScale: 34,
    dropletStretch: 1.8,
    edgeStrength: 0.22,
    highlightStrength: 0.38,
    reflectionStrength: 0.12,
    gravity: 0.008,
    trailStrength: 0.16,
  },
  hand: {
    boundingBoxRadius: 0.175,
    palmRadiusMultiplier: 2.8,
    fingertipRadius: 0.055,
    singleFingerExtensionRatio: 1.12,
    brushSoftness: 0.72,
  },
  mouth: {
    jawOpenThreshold: 0.42,
    refillRadius: 0.075,
    smoothing: 0.18,
    plumeLength: 0.34,
    plumeWidth: 0.11,
    plumeStrength: 0.7,
    plumeNoiseScale: 24,
    puckerThreshold: 0.65,
    emitterWidth: 0.18,
    emitterHeight: 1.38,
    particleDepthTravel: 1.72,
    particleMaxSize: 960,
    particleConeXSpread: 2.8,
    particleConeYSpread: 10.56,
    burstDuration: 1.8,
    particleLifetimeMin: 1.1,
    particleLifetimeMax: 2.0,
    particleSpawnStagger: 0.35,
    autoRefillInterval: 3,
    autoRefillDuration: 1,
    autoRefillRadius: 0.075,
    autoRefillStrength: 12,
    frostBloomRadius: 0.24,
    frostBloomStrength: 0.34,
  },
  tracking: { targetFps: 24 },
} as const;

export type SnowyWindowConfig = typeof SNOWY_WINDOW_CONFIG;
